apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./rabbitmq-secret.yaml
  - ./suite-runner-configmap.yaml

patchesStrategicMerge:
  - ./configmap.yaml
  - ./deployment.yaml

commonLabels:
    app.kubernetes.io/instance: etos-development

images:
- name: registry.nordix.org/eiffel/etos-suite-starter
  newTag: "2.0.1"

# Might seem unnecessary to patch a file that is already in the overlay,
# this patch is done so that our CI jobs only have to know the format of
# the kustomization.yaml file and not any others. The CI job should
# only have to update the image below in order to deploy the correct
# version.
patches:
- patch: |-
    - op: replace
      path: "/data/SUITE_RUNNER"
      value: registry.nordix.org/eiffel/etos-suite-runner:3.1.0
    - op: add  # TODO: Change to replace when releasing 5.0.0
      path: "/data/LOG_LISTENER"
      value: registry.nordix.org/eiffel/etos-log-listener:3.1.0
  target:
    kind: ConfigMap
    labelSelector: app.kubernetes.io/name=etos-suite-starter

# This is a workaround for secrets not generating a reload
# of pods. By loading the sealed secret into a generated
# configmap, the configmap will get a new name any time the
# sealed secret is changed resulting in a reload of the
# deployment.
# In order to have this behavior it was either this workaround
# or creating a plugin to kustomize. I chose this since this
# will work natively in ArgoCD.
configMapGenerator:
  - name: etos-suite-starter-sealed-secret
    files:
    - rabbitmq-secret.yaml
generatorOptions:
  labels:
    app.kubernetes.io/name: etos-suite-starter
    app.kubernetes.io/instance: etos-development
