apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etos-firmware-flasher
  labels:
    app.kubernetes.io/name: etos-firmware-flasher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etos-firmware-flasher
  minReplicas: 10
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
