apiVersion: v1
kind: Service
metadata:
  name: etos-firmware-flasher
  labels:
    app.kubernetes.io/name: etos-firmware-flasher
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: etos-firmware-flasher
