apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: etos-(api|suite-starter|environment-provider|environment-provider-worker)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts/-
      value:
        name: shared-logs
        mountPath: /home/etos/logs
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: shared-logs
        emptyDir: {}
    - op: add
      path: /spec/template/spec/volumes/-
      value:
        name: filebeat-config
        configMap:
          name: etos-filebeat-config
    - op: add
      path: /spec/template/spec/containers/-
      value:
        name: sidecar
        image: docker.elastic.co/beats/filebeat:7.10.1
        volumeMounts:
        - name: shared-logs
          mountPath: /usr/share/filebeat/logs
        - name: filebeat-config
          mountPath: /usr/share/filebeat/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
- target:
    kind: ConfigMap
    name: etos-suite-starter
  patch: |-
    - op: add
      path: /data/ETOS_SIDECAR_ENABLED
      value: "true"
    - op: add
      path: /data/ETOS_SIDECAR_IMAGE
      value: docker.elastic.co/beats/filebeat:7.10.1
