apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./worker/rabbitmq-secret.yaml
  - ./worker/encryption-key.yaml
  - ./api/execution-space-providers.yaml
  - ./api/iut-providers.yaml
  - ./api/log-area-providers.yaml
  - ./redis-secret.yaml
  - ./ssh-key.yaml
  - ./api/autoscaler.yaml
  - ./worker/autoscaler.yaml

patchesStrategicMerge:
  - ./api/configmap.yaml
  - ./api/deployment.yaml
  - ./worker/configmap.yaml
  - ./worker/deployment.yaml

commonLabels:
    app.kubernetes.io/instance: etos-production

# Having the sealed secrets here is a workaround for secrets
# not generating a reload of pods.
# By loading the sealed secret into a generated
# configmap, the configmap will get a new name any time the
# sealed secret is changed resulting in a reload of the
# deployment.
# In order to have this behavior it was either this workaround
# or creating a plugin to kustomize. I chose this since this
# will work natively in ArgoCD.
configMapGenerator:
  - name: etos-environment-provider-worker-secrets
    files:
    - worker/rabbitmq-secret.yaml
    - worker/encryption-key.yaml
    - redis-secret.yaml
  - name: etos-environment-provider-secrets
    files:
    - redis-secret.yaml
    - api/execution-space-providers.yaml
    - api/log-area-providers.yaml
    - api/iut-providers.yaml
  - name: etos-environment-provider-filebeat-config
    files:
    - filebeat.yml
generatorOptions:
  labels:
    app.kubernetes.io/name: etos-environment-provider
    app.kubernetes.io/instance: etos-production
