apiVersion: batch/v1
kind: Job
metadata:
  name: load-provider-json
  labels:
    app.kubernetes.io/name: etos
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 10
  template:
    spec:
      volumes:
      - name: ssh-key
        secret:
          secretName: etos-ssh-key
          defaultMode: 256
      - name: provider-json
        emptyDir: {}
      initContainers:
      - name: clone-provider-json
        image: "alpine/git"
        args:
          - "clone"
          - "ssh://gittools.se.axis.com:29418/tools/test/etos/provider_json"
          - "/provider_json"
        env:
        - name: GIT_SSH_COMMAND
          value: "ssh -i /.ssh/id_rsa -l svcetos -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        volumeMounts:
        - name: ssh-key
          readOnly: true
          mountPath: "/.ssh"
        - name: provider-json
          mountPath: "/provider_json"
      containers:
      - name: deploy-provider-json
        image: "alpine/curl"
        workingDir: /provider_json/production
        command:
          - "/bin/sh"
        args:
          - "./deploy.sh"
        volumeMounts:
        - name: provider-json
          mountPath: "/provider_json"
      restartPolicy: Never
