apiVersion: v1
stringData:
  name: ETOS Elastic
  project: etos
  type: helm
  url: https://helm.elastic.co
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: etos-elastic
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  name: ETOS Bitnami
  project: etos
  type: helm
  url: https://charts.bitnami.com/bitnami
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: etos-bitnami
  namespace: argocd
type: Opaque
---
apiVersion: v1
stringData:
  name: ETOS
  project: etos
  url: https://gittools.se.axis.com/gerrit/a/system/etos/ops
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: etos
  namespace: argocd
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: etos
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: ETOS
  destinations:
  - name: in-cluster
    namespace: etos-production
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: etos-staging
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: etos-development
    server: https://kubernetes.default.svc
  - name: in-cluster
    namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://gittools.se.axis.com/gerrit/a/system/etos/ops
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-staging
  namespace: argocd
spec:
  destination:
    namespace: etos-staging
    server: https://kubernetes.default.svc
  project: etos
  source:
    path: overlays/staging
    repoURL: https://gittools.se.axis.com/gerrit/a/system/etos/ops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-staging-redis
  namespace: argocd
spec:
  destination:
    namespace: etos-staging
    server: https://kubernetes.default.svc
  project: etos
  source:
    chart: redis
    targetRevision: 16.13.2
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      values: |
        auth:
          existingSecret: etos-database
          existingSecretPasswordKey: ETOS_DATABASE_PASSWORD
        sentinel:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-staging-logstash
  namespace: argocd
spec:
  destination:
    namespace: etos-staging
    server: https://kubernetes.default.svc
  project: etos
  source:
    chart: logstash
    targetRevision: 7.17.3
    repoURL: https://helm.elastic.co
    helm:
      # maxUnavailable created a PodDisruptionBudget which only works in v1.21.0+ of k8s
      values: |
        maxUnavailable: null
        envFrom:
        - secretRef:
            name: etos-elasticsearch-password
        service:
          type: LoadBalancer
          loadBalancerIP: 172.27.100.72
          ports:
            - name: beats
              protocol: TCP
              port: 5044
              targetPort: 5044
        logstashConfig:
          logstash.yml: |-
            http.host: 0.0.0.0
        logstashPipeline:
          logstash.conf: |
            input {
              beats {
                port => 5044
              }
            }
            filter {
              json {
                source => "message"
              }
              date{
                match => ["timestamp", "UNIX_MS"]
                target => "@timestamp"
              }
            }
            output {
              elasticsearch {
                user => elastic
                hosts => ["kibana.axisqa.com:9200"]
                password => "${ELASTICSEARCH_PASSWORD}"
                codec => json
              }
            }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-production
  namespace: argocd
spec:
  destination:
    namespace: etos-production
    server: https://kubernetes.default.svc
  project: etos
  source:
    path: overlays/production
    repoURL: https://gittools.se.axis.com/gerrit/a/system/etos/ops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-production-logstash
  namespace: argocd
spec:
  destination:
    namespace: etos-production
    server: https://kubernetes.default.svc
  project: etos
  source:
    chart: logstash
    targetRevision: 7.17.3
    repoURL: https://helm.elastic.co
    helm:
      # maxUnavailable created a PodDisruptionBudget which only works in v1.21.0+ of k8s
      values: |
        maxUnavailable: null
        envFrom:
        - secretRef:
            name: etos-elasticsearch-password
        service:
          type: LoadBalancer
          loadBalancerIP: 172.27.100.73
          ports:
            - name: beats
              protocol: TCP
              port: 5044
              targetPort: 5044
        logstashConfig:
          logstash.yml: |-
            http.host: 0.0.0.0
        logstashPipeline:
          logstash.conf: |
            input {
              beats {
                port => 5044
              }
            }
            filter {
              json {
                source => "message"
              }
              date{
                match => ["timestamp", "UNIX_MS"]
                target => "@timestamp"
              }
            }
            output {
              elasticsearch {
                user => elastic
                hosts => ["kibana.axisqa.com:9200"]
                password => "${ELASTICSEARCH_PASSWORD}"
                codec => json
              }
            }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-production-redis
  namespace: argocd
spec:
  destination:
    namespace: etos-production
    server: https://kubernetes.default.svc
  project: etos
  source:
    chart: redis
    targetRevision: 16.13.2
    repoURL: https://charts.bitnami.com/bitnami
    helm:
      values: |
        auth:
          existingSecret: etos-database
          existingSecretPasswordKey: ETOS_DATABASE_PASSWORD
        sentinel:
          enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
