apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-suite-starter
  labels:
    app.kubernetes.io/name: etos-suite-starter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-suite-starter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-suite-starter
    spec:
      serviceAccountName: etos-suite-starter
      containers:
        - name: etos-suite-starter
          image: "registry.nordix.org/eiffel/etos-suite-starter:1.29.0"
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: etos-suite-starter
