apiVersion: v2
name: environment-provider-workers
description: These are the workers for handling environments making it possible to checkout and check in
  environments for use in testing with ETOS.
type: application
version: 2.1.1
appVersion: 1.32.2

keywords:
  - Test automation
  - Eiffel

home: https://etos.readthedocs.io/

maintainers:
  - name: Anders Josephson
    email: anders.josephson@axis.com
  - name: Fredrik Fristedt
    email: fredrik.fristedt@axis.com
  - name: Tobias Persson
    email: tobias.persson@axis.com
