apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-environment-provider
  labels:
    app.kubernetes.io/name: etos-environment-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-environment-provider
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-environment-provider
    spec:
      serviceAccountName: etos-environment-provider
      containers:
        - name: etos-environment-provider
          image: "registry.nordix.org/eiffel/etos-environment-provider:1.36.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /?id=healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /?id=healthcheck
              port: http
