apiVersion: v1
kind: Service
metadata:
  name: etos-environment-provider
  labels:
    app.kubernetes.io/name: etos-environment-provider
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: etos-environment-provider
