apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-environment-provider
spec:
  template:
    spec:
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: etos-environment-provider-filebeat-config
      - name: execution-space-providers
        secret:
          secretName: execution-space-providers
      - name: log-area-providers
        secret:
          secretName: log-area-providers
      - name: iut-providers
        secret:
          secretName: iut-providers
      containers:
        - name: etos-environment-provider
          env:
          - name: EXECUTION_SPACE_PROVIDERS
            value: /providers/execution_space
          - name: LOG_AREA_PROVIDERS
            value: /providers/log_area
          - name: IUT_PROVIDERS
            value: /providers/iut
          envFrom:
          - configMapRef:
              name: etos-environment-provider-secrets
          - configMapRef:
              name: etos-environment-provider
          - secretRef:
              name: etos-environment-provider-database
          volumeMounts:
          - name: shared-logs
            mountPath: /home/etos/logs
          - name: execution-space-providers
            readOnly: true
            mountPath: "/providers/execution_space"
          - name: log-area-providers
            readOnly: true
            mountPath: "/providers/log_area"
          - name: iut-providers
            readOnly: true
            mountPath: "/providers/iut"
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 512Mi
        - name: sidecar
          image: docker.elastic.co/beats/filebeat:7.10.1
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/filebeat/logs
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
