apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: etos-sse
  name: etos-sse
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: etos-sse
  type: ClusterIP
