apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-otel
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      otlp:
        endpoint: jaeger-collector-headless.observability.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        logs:
          exporters:
            - otlp
          processors: []
          receivers:
            - otlp
        traces:
          exporters:
            - otlp
          processors: []
          receivers:
            - otlp
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: static-otel
spec:
  mode: statefulset
  config: |
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
    exporters:
      otlp:
        endpoint: jaeger-collector-headless.observability.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: debug
      pipelines:
        logs:
          exporters:
            - otlp
          processors: []
          receivers:
            - otlp
        traces:
          exporters:
            - otlp
          processors: []
          receivers:
            - otlp
