apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: etos-environment-provider-worker
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        secretRef:
          name: etos-encryption-key
- target:
    kind: Deployment
    name: etos-logarea
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value:
      - secretRef:
          name: etos-encryption-key

# Update the ESR RabbitMQ secret
replacements:
  - source:
      kind: SealedSecret
      name: etos-encryption-key
      fieldPath: spec.encryptedData.ETOS_ENCRYPTION_KEY
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_ENCRYPTION_KEY
      options:
        create: true
