apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-firmware-flasher-staging
  namespace: argocd
spec:
  destination:
    namespace: etos-staging
    server: https://kubernetes.default.svc
  project: etos
  source:
    path: firmware-flasher/overlays/staging
    repoURL: https://gittools.se.axis.com/gerrit/a/system/etos/ops
    targetRevision: user/tobiaspn/test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
