apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: etos-staging

resources:
  - github.com/eiffel-community/etos//manifests/release
  - ./namespace.yaml
  - ./resources/secrets/elasticsearch-password.yaml
  - ./resources/secrets/rabbitmq-secret.yaml
  - ./resources/secrets/esr-rabbitmq-secret.yaml
  - ./resources/secrets/encryption-key.yaml
  - ./resources/secrets/user-logs-secret.yaml
  - ./resources/secrets/database-secret.yaml
  - ./resources/providers/iut-providers.yaml
  - ./resources/providers/execution-space-providers.yaml
  - ./resources/providers/log-area-providers.yaml
  - ./resources/suite-runner-filebeat.yaml

commonLabels:
  app.kubernetes.io/instance: etos-staging

patches:
- target:
    kind: SealedSecret
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1instance
      value: etos-staging
    - op: add
      path: /spec/template/metadata/labels/app.kubernetes.io~1instance
      value: etos-staging
- target:
    kind: ConfigMap
    name: (etos|etos-suite-runner)
  patch: |-
    - op: add
      path: /data/ETOS_API
      value: http://etos.etos-staging.k8s.axis.com/api
    - op: add
      path: /data/ETOS_ROUTING_KEY_TAG
      value: etos-staging
- target:
    kind: ConfigMap
    name: etos-suite-starter
  patch: |-
    - op: replace
      path: /data/RABBITMQ_QUEUE
      value: svcetos.suite_starter.staging
    - op: replace
      path: /data/RABBITMQ_ROUTING_KEY
      value: eiffel.*.EiffelTestExecutionRecipeCollectionCreatedEvent.etos-staging.*
- target:
    kind: Ingress
    name: etos
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "etos.etos-staging.k8s.axis.com"
    - op: add
      path: /spec/rules/-
      value:
        host: "firmware-api.etos-staging.k8s.axis.com"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: etos-firmware-flasher
                  port:
                    number: 80

configMapGenerator:
  - name: etos-filebeat-config
    files:
    - ./filebeat.yml
  - name: reload
    behavior: merge
    files:
    - ./resources/secrets/database-secret.yaml
    - ./resources/secrets/rabbitmq-secret.yaml
    - ./resources/secrets/encryption-key.yaml
    - ./resources/secrets/user-logs-secret.yaml
    - ./resources/providers/execution-space-providers.yaml
    - ./resources/providers/log-area-providers.yaml
    - ./resources/providers/iut-providers.yaml
generatorOptions:
  labels:
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/instance: etos-staging

components:
  - ../../components/base
  # Reloader generates a configmap that we can merge in reloadable items to.
  # The reloader component should be loaded before any that want to merge.
  - ../../components/reloader

  - ../../components/autoscaling
  - ../../components/filebeat-opentelemetry
  - ../../components/rabbitmq
  - ../../components/encryption
  - ../../components/user-logs
  # Provider sealed secrets need to have been created
  - ../../components/providers
  - ../../components/observability
