apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-staging-logstash
  namespace: argocd
spec:
  destination:
    namespace: etos-staging
    server: https://kubernetes.default.svc
  project: etos
  source:
    chart: logstash
    targetRevision: 7.17.3
    repoURL: https://helm.elastic.co
    helm:
      # maxUnavailable created a PodDisruptionBudget which only works in v1.21.0+ of k8s
      values: |
        maxUnavailable: null
        envFrom:
        - secretRef:
            name: etos-elasticsearch-password
        service:
          type: ClusterIP
          ports:
            - name: beats
              port: 5044
              protocol: TCP
              targetPort: 5044
        logstashConfig:
          logstash.yml: |-
            http.host: 0.0.0.0
        logstashPipeline:
          logstash.conf: |
            input {
              beats {
                port => 5044
              }
            }
            filter {
              json {
                source => "message"
              }
              date{
                match => ["timestamp", "UNIX_MS"]
                target => "@timestamp"
              }
            }
            output {
              elasticsearch {
                user => elastic
                hosts => ["kibana.axisqa.com:9200"]
                password => "${ELASTICSEARCH_PASSWORD}"
                codec => json
              }
            }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
