apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-api
  labels:
    app.kubernetes.io/name: etos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: etos-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: etos-api
    spec:
      serviceAccountName: etos-api
      containers:
        - name: etos-api
          image: "registry.nordix.org/eiffel/etos-api:1.28.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /selftest/ping
              port: http
          readinessProbe:
            httpGet:
              path: /selftest/ping
              port: http
