apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: etos-api
  name: etos-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etos-api:sa:pod-reader
subjects:
- kind: ServiceAccount
  name: etos-api
