apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etos.name" . }}
  
data:
  DEV: {{ .Values.global.development | quote }}

  {{- include "etos.suiteRunnerContainerImage" . | indent 2 }}
  HTTP_PROXY_OVERRIDE: {{ if eq .Values.httpProxy ""}}""{{ else }}{{ .Values.httpProxy }}{{ end }}
  HTTPS_PROXY_OVERRIDE: {{ if eq .Values.httpsProxy ""}}""{{ else }}{{ .Values.httpsProxy }}{{ end }}
  SOURCE_HOST: {{ include "etos.name" . | upper }}

  ETOS_NAMESPACE: {{ .Release.Namespace}}
  ETOS_CONFIGMAP: {{ include "etos.name" . }}

  ETOS_GRAPHQL_SERVER: {{ .Values.global.graphqlServerUrl }}
  ETOS_ENVIRONMENT_PROVIDER: {{ .Values.global.environmentProviderUrl }}
  ETOS_API: {{ .Values.global.etosApiUrl }}

  ETOS_SECRET_PATH: {{ .Values.secretPath }}
  ETOS_DEFAULT_HTTP_TIMEOUT: {{ .Values.defaultHttpTimeout | quote }}
  ETOS_DEFAULT_WAIT_TIMEOUT: {{ .Values.defaultWaitTimeout | quote }}
  ETOS_DEFAULT_TEST_RESULT_TIMEOUT: {{ .Values.defaultTestResultTimeout | quote }}
  ETOS_PUBLISHED_EVENT_HISTORY_SIZE: {{ .Values.publishedEventHistorySize | quote }}
  ETOS_RECEIVED_EVENT_HISTORY_SIZE: {{ .Values.receivedEventHistorySize | quote }}

  # ETOS_DISABLE_SENDING_EVENTS: "1"
  # ETOS_DISABLE_RECEIVING_EVENTS: "1"
  # ETOS_DISABLE_MONITOR_ANNOUNCE: "1"

  ETOS_DATABASE_HOST: {{ .Values.databaseHost }}
  ETOS_DATABASE_PORT: {{ .Values.databasePort | quote }}

  RABBITMQ_HOST: {{ .Values.rabbitmqHost }}
  RABBITMQ_EXCHANGE: {{ .Values.rabbitmqExchange }}
  RABBITMQ_PORT: {{ .Values.rabbitmqPort | quote }}
  RABBITMQ_VHOST: {{ .Values.rabbitmqVhost }}
  RABBITMQ_SSL: {{ .Values.rabbitmqSSL | quote }}

  ENVIRONMENT_PROVIDER_GRAPHQL_QUERY_TIMEOUT: {{ .Values.environmentProviderGraphqlQueryTimeout | quote }}
  ENVIRONMENT_PROVIDER_EVENT_DATA_TIMEOUT: {{ .Values.environmentProviderEventDataTimeout | quote }}
  ENVIRONMENT_PROVIDER_TEST_SUITE_TIMEOUT: {{ .Values.environmentProviderTestSuiteTimeout | quote }}

  # Environment provider checks for device every 5s. This means that we should always
  # wait for a longer time than that. Recommended is to add 10s, just to be safe.
  ESR_WAIT_FOR_ENVIRONMENT_TIMEOUT: {{ .Values.esrWaitForEnvironmentTimeout | quote }}
  
