apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap }}
  labels:
    {{- include "etos.labels" . | nindent 4 }}
data:
  DEV: {{ .Values.global.development | quote }}

  SUITE_RUNNER: {{ .Values.suiteRunner.image }}:{{ .Values.suiteRunner.tag }}

  ETOS_GRAPHQL_SERVER: {{ required "ETOS requires an Eiffel GraphQL API instance`" .Values.graphql.host }}
  ETOS_ENVIRONMENT_PROVIDER: {{ required "ETOS requires the environment provider host to be set" .Values.hosts.environmentProvider }}
  ETOS_API: {{ required "ETOS requires the API host to be set" .Values.hosts.API }}

  {{- if .Values.suiteRunner.filebeat.eneabled }}
  # Quoted sidecar enabled is required for suite-starter to pass this over to suite-runner.
  ETOS_SIDECAR_ENABLED: {{ .Values.suiteRunner.filebeat.enabled | quote}}
  ETOS_SIDECAR_IMAGE: {{ .Values.suiteRunner.filebeat.image }}
  {{- end }}

  SOURCE_HOST: {{ include "etos.name" . | upper }}

  ETOS_NAMESPACE: {{ .Release.Namespace}}
  ETOS_CONFIGMAP: {{ .Values.configMap }}
  ETOS_ROUTING_KEY_TAG: {{ .Values.routingKey.tag }}

  RABBITMQ_HOST: {{ required "Please set `rabbitmq.host`" .Values.rabbitmq.host }}
  RABBITMQ_EXCHANGE: {{ required "Please set `rabbitmq.exchange`" .Values.rabbitmq.exchange }}
  RABBITMQ_PORT: {{ required "Please set `rabbitmq.port`" .Values.rabbitmq.port | quote }}
  RABBITMQ_VHOST: {{ required "Please set `rabbitmq.vhost`" .Values.rabbitmq.vhost }}
  RABBITMQ_SSL: {{ required "Please set `rabbitmq.ssl`" .Values.rabbitmq.ssl | quote }}

  ETOS_DATABASE_HOST: {{ required "Please set `database.host`" .Values.database.host }}
  ETOS_DATABASE_PORT: {{ required "Please set `database.port`" .Values.database.port | quote }}

  {{- if .Values.config }}
  {{- range $key, $value := .Values.config }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end -}}
  {{- end }}
