{{- if eq .Values.global.existingDatabaseSecret "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseSecret }}
  labels:
    {{- include "etos.labels" . | nindent 4 }}
type: Opaque
data:
  ETOS_DATABASE_PASSWORD: {{ .Values.database.password | default "" | b64enc }}
stringData:
  ETOS_DATABASE_HOST: {{ required "Please set `database.host`" .Values.database.host }}
  ETOS_DATABASE_PORT: {{ required "Please set `database.port`" .Values.database.port | quote }}
{{- end }}
