{{- if eq .Values.global.existingRabbitmqSecret "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmqSecret }}
  labels:
    {{- include "etos.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | default "" | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | default "" | b64enc }}
stringData:
  RABBITMQ_HOST: {{ required "Please set `rabbitmq.host`" .Values.rabbitmq.host }}
  RABBITMQ_EXCHANGE: {{ required "Please set `rabbitmq.exchange`" .Values.rabbitmq.exchange }}
  RABBITMQ_PORT: {{ required "Please set `rabbitmq.port`" .Values.rabbitmq.port | quote }}
  RABBITMQ_VHOST: {{ required "Please set `rabbitmq.vhost`" .Values.rabbitmq.vhost }}
  RABBITMQ_SSL: {{ required "Please set `rabbitmq.ssl`" .Values.rabbitmq.ssl | quote }}
{{- end }}
