apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    {{- include "etos.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | default "" | b64enc }}
  password: {{ .Values.rabbitmq.password | default "" | b64enc }}