{{- if eq .Values.global.existingRabbitmqSecret "" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmqSecret }}
  labels:
    {{- include "etos.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | default "" | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | default "" | b64enc }}
stringData:
  RABBITMQ_HOST: {{ required "Please set `rabbitmq.host`" .Values.rabbitmq.host }}
  RABBITMQ_EXCHANGE: {{ required "Please set `rabbitmq.exchange`" .Values.rabbitmq.exchange }}
  RABBITMQ_PORT: {{ required "Please set `rabbitmq.port`" .Values.rabbitmq.port | quote }}
  RABBITMQ_VHOST: {{ required "Please set `rabbitmq.vhost`" .Values.rabbitmq.vhost }}
  RABBITMQ_SSL: {{ required "Please set `rabbitmq.ssl`" .Values.rabbitmq.ssl | quote }}
  ETOS_RABBITMQ_HOST: {{ required "Please set `logging.rabbitmq.host`" .Values.logging.rabbitmq.host }}
  ETOS_RABBITMQ_EXCHANGE: {{ required "Please set `logging.rabbitmq.exchange`" .Values.logging.rabbitmq.exchange }}
  ETOS_RABBITMQ_PORT: {{ required "Please set `logging.rabbitmq.port`" .Values.logging.rabbitmq.port | quote }}
  ETOS_RABBITMQ_VHOST: {{ required "Please set `logging.rabbitmq.vhost`" .Values.logging.rabbitmq.vhost }}
  ETOS_RABBITMQ_SSL: {{ required "Please set `logging.rabbitmq.ssl`" .Values.logging.rabbitmq.ssl | quote }}
  ETOS_RABBITMQ_QUEUE_NAME: {{ required "Please set `logging.rabbitmq.queue`" .Values.logging.rabbitmq.queue }}
{{- end }}
