{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "etos.labels" . | nindent 4 }}
  name: {{ include "etos.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}:sa:job-creator
subjects:
- kind: ServiceAccount
  name: {{ include "etos.serviceAccountName" . }}
{{- end }}