apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "etos.serviceAccountName" . | indent 2}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Namespace }}:sa:job-creator
subjects:
- kind: ServiceAccount
  name: {{ include "etos.serviceAccountName" . }}
  
