apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: etos-production

resources:
  - github.com/eiffel-community/etos//manifests/release?ref=6.3.0
  - ./namespace.yaml
  - ./resources/secrets/elasticsearch-password.yaml
  - ./resources/secrets/rabbitmq-secret.yaml
  - ./resources/secrets/esr-rabbitmq-secret.yaml
  - ./resources/secrets/encryption-key.yaml
  - ./resources/secrets/user-logs-secret.yaml
  - ./resources/secrets/database-secret.yaml
  - ./resources/providers/iut-providers.yaml
  - ./resources/providers/execution-space-providers.yaml
  - ./resources/providers/log-area-providers.yaml
  - ./resources/suite-runner-filebeat.yaml

commonLabels:
  app.kubernetes.io/instance: etos-production

patches:
- target:
    kind: SealedSecret
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1instance
      value: etos-production
    - op: add
      path: /spec/template/metadata/labels/app.kubernetes.io~1instance
      value: etos-production
- target:
    kind: ConfigMap
    name: (etos|etos-suite-runner)
  patch: |-
    - op: add
      path: /data/ETOS_API
      value: http://etos.etos.k8s.axis.com/api
    - op: add
      path: /data/ETOS_ROUTING_KEY_TAG
      value: etos-prod
- target:
    kind: ConfigMap
    name: etos-suite-starter
  patch: |-
    - op: replace
      path: /data/RABBITMQ_QUEUE
      value: svcetos.suite_starter.prod
    - op: replace
      path: /data/RABBITMQ_ROUTING_KEY
      value: eiffel.*.EiffelTestExecutionRecipeCollectionCreatedEvent.etos-prod.*
- target:
    kind: ConfigMap
    name: etos-environment-provider-worker
  # TODO: This patch shall be removed on the next ETOS release
  patch: |-
    - op: replace
      path: /data/ETR_VERSION
      value: 3.4.0
- target:
    kind: Ingress
    name: etos
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "etos.etos.k8s.axis.com"
    - op: add
      path: /spec/rules/-
      value:
        host: "firmware-api.etos.k8s.axis.com"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: etos-firmware-flasher
                  port:
                    number: 80

configMapGenerator:
  - name: etos-filebeat-config
    files:
    - ./filebeat.yml
  - name: reload
    files:
    - ./resources/secrets/database-secret.yaml
    - ./resources/secrets/rabbitmq-secret.yaml
    - ./resources/secrets/encryption-key.yaml
    - ./resources/secrets/user-logs-secret.yaml
    - ./resources/providers/execution-space-providers.yaml
    - ./resources/providers/log-area-providers.yaml
    - ./resources/providers/iut-providers.yaml
generatorOptions:
  labels:
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/instance: etos-production

components:
  - ../../components/base
  - ../../components/autoscaling

  - ../../components/filebeat
  - ../../components/rabbitmq
  - ../../components/encryption
  - ../../components/user-logs
  # Provider sealed secrets need to have been created
  - ../../components/providers
  # A generated configmap named 'reload' must be created for the reloader.
  - ../../components/reloader
  - ../../components/firmware-flasher
  - ../../components/cleaning-crew
