apiVersion: v2
name: api
description: API for starting ETOS executions and for getting extra information about
  the system.
type: application
version: 2.1.1
appVersion: 1.29.0

keywords:
  - Test automation
  - Eiffel

home: https://etos.readthedocs.io/

maintainers:
  - name: Anders Josephson
    email: anders.josephson@axis.com
  - name: Fredrik Fristedt
    email: fredrik.fristedt@axis.com
  - name: Tobias Persson
    email: tobias.persson@axis.com
