# permissions for end users to edit environmentrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: environmentrequest-editor-role
rules:
- apiGroups:
  - etos.eiffel-community.github.io
  resources:
  - environmentrequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - etos.eiffel-community.github.io
  resources:
  - environmentrequests/status
  verbs:
  - get
