# This rule is not used by the project etos itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over etos.eiffel-community.github.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: etos
    app.kubernetes.io/managed-by: kustomize
  name: provider-admin-role
rules:
- apiGroups:
  - etos.eiffel-community.github.io
  resources:
  - providers
  verbs:
  - '*'
- apiGroups:
  - etos.eiffel-community.github.io
  resources:
  - providers/status
  verbs:
  - get
