apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-suite-starter-development
  namespace: argocd
spec:
  destination:
    namespace: etos-development
    server: https://kubernetes.default.svc
  project: etos
  source:
    path: etos-suite-starter/overlays/development
    repoURL: https://gittools.se.axis.com/gerrit/a/system/etos/ops
    targetRevision: HEAD
