apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etos-firmware-flasher-development
  namespace: argocd
spec:
  destination:
    namespace: etos-development
    server: https://kubernetes.default.svc
  project: etos
  source:
    path: firmware-flasher/overlays/development
    repoURL: https://gittools.se.axis.com/gerrit/a/system/etos/ops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
