apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: etos-development

resources:
  - github.com/eiffel-community/etos//manifests/master
  - ./namespace.yaml
  - ./resources/secrets/elasticsearch-password.yaml
  - ./resources/secrets/rabbitmq-secret.yaml
  - ./resources/secrets/esr-rabbitmq-secret.yaml
  - ./resources/secrets/encryption-key.yaml
  - ./resources/secrets/user-logs-secret.yaml
  - ./resources/secrets/database-secret.yaml
  - ./resources/secrets/etos-executionspace-rabbitmq-secret.yaml
  - ./resources/secrets/etos-executionspace-ssh-key.yaml
  - ./resources/providers/iut-providers.yaml
  - ./resources/providers/execution-space-providers.yaml
  - ./resources/providers/log-area-providers.yaml
  - ./resources/suite-runner-filebeat.yaml

commonLabels:
  app.kubernetes.io/instance: etos-development

patches:
- target:
    kind: SealedSecret
  patch: |-
    - op: add
      path: /metadata/labels/app.kubernetes.io~1instance
      value: etos-development
    - op: add
      path: /spec/template/metadata/labels/app.kubernetes.io~1instance
      value: etos-development
- target:
    kind: ConfigMap
    name: (etos-suite-runner|etos-suite-starter|etos-api)
  patch: |-
    - op: add
      path: /data/DEV
      value: "true"
- target:
    kind: ConfigMap
    name: (etos|etos-suite-runner)
  patch: |-
    - op: add
      path: /data/ETOS_API
      value: http://etos.etos-dev.k8s.axis.com/api
    - op: add
      path: /data/ETOS_ROUTING_KEY_TAG
      value: etos-dev
    - op: add
      path: /data/OTEL_COLLECTOR_HOST
      value: static-otel-collector.etos-development.svc.cluster.local:4317
- target:
    kind: ConfigMap
    name: etos-suite-starter
  patch: |-
    - op: replace
      path: /data/RABBITMQ_QUEUE
      value: svcetos.suite_starter.dev
    - op: replace
      path: /data/RABBITMQ_ROUTING_KEY
      value: eiffel.*.EiffelTestExecutionRecipeCollectionCreatedEvent.etos-dev.*
    - op: add
      path: /data/ETOS_OBSERVABILITY_CONFIGMAP
      value: etos-observability
- target:
    kind: ConfigMap
    name: etos-executionspace
  patch: |-
    - op: add
      path: /data/EXECUTOR_HTTPS_PROXY
      value: http://wwwproxy.se.axis.com:3128
    - op: add
      path: /data/EXECUTOR_HTTP_PROXY
      value: http://wwwproxy.se.axis.com:3128
    - op: add
      path: /data/EXECUTOR_NO_PROXY
      value: "localhost,127.0.0.1,127.0.1.1,.localdomain,.axis.com,.k3d.internal"
    - op: add
      path: /data/EXECUTOR_TZ
      value: "Europe/Stockholm"
    - op: add
      path: /data/ETOS_NAMESPACE
      value: etos-development
    - op: add
      path: /data/REQUEST_TIMEOUT
      value: "1h"
    - op: add
      path: /data/EXECUTION_SPACE_WAIT_TIMEOUT
      value: "10s"
    - op: add
      path: /data/EIFFEL_GOER_URL
      value: https://eiffel-er-prod.se.axis.com/v1/events
- target:
    kind: Ingress
    name: etos
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "etos.etos-dev.k8s.axis.com"
    - op: add
      path: /spec/rules/-
      value:
        host: "firmware-api.etos-dev.k8s.axis.com"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: etos-firmware-flasher
                  port:
                    number: 80

configMapGenerator:
  - name: etos-filebeat-config
    files:
    - ./filebeat.yml
  - name: reload
    behavior: merge
    files:
    - ./resources/secrets/database-secret.yaml
    - ./resources/secrets/rabbitmq-secret.yaml
    - ./resources/secrets/encryption-key.yaml
    - ./resources/secrets/user-logs-secret.yaml
    - ./resources/providers/execution-space-providers.yaml
    - ./resources/providers/log-area-providers.yaml
    - ./resources/providers/iut-providers.yaml
    - ./resources/secrets/etos-executionspace-rabbitmq-secret.yaml
    - ./resources/secrets/etos-executionspace-ssh-key.yaml
generatorOptions:
  labels:
    app.kubernetes.io/part-of: etos
    app.kubernetes.io/instance: etos-development

components:
  - ../../components/base
  - ../../components/reloader
  - ../../components/filebeat-opentelemetry
  - ../../components/autoscaling
  - ../../components/rabbitmq
  - ../../components/rabbitmq-executionspace
  - ../../components/encryption
  - ../../components/user-logs
  # Provider sealed secrets need to have been created
  - ../../components/providers
  # A generated configmap named 'reload' must be created for the reloader.
  - ../../components/observability
