[tox]
envlist = py3,black,pylint,pydocstyle

[testenv]
deps =
    -r{toxinidir}/test-requirements.txt
commands =
    pytest -s --log-format="%(levelname)s: %(message)s" {posargs}

[testenv:black]
deps =
    black
commands =
    black --check --diff -l 100 .

[testenv:pylint]
deps =
    pylint
    pytest
commands =
    pylint -d duplicate-code src/etos_client src/etosctl src/etos_debug tests

[testenv:pydocstyle]
deps =
    pydocstyle
    tomli
commands =
    pydocstyle src/etos_client src/etosctl src/etos_debug
