[tox]
envlist = black,pylint,pydocstyle

[testenv:black]
deps =
    black
commands =
    black --check --diff -l 100 .

[testenv:pylint]
deps =
    pylint
    pytest
commands =
    pylint -d duplicate-code src/etos_client src/etosctl src/etos_debug tests

[testenv:pydocstyle]
deps =
    pydocstyle
    tomli
commands =
    pydocstyle src/etos_client src/etosctl src/etos_debug
