apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-environment-provider-worker
spec:
  template:
    spec:
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: etos-environment-provider-filebeat-config
      containers:
        - name: etos-environment-provider-worker
          envFrom:
          - configMapRef:
              name: etos-environment-provider-worker-secrets
          - configMapRef:
              name: etos-environment-provider-worker
          - secretRef:
              name: etos-environment-provider-worker-rabbitmq
          - secretRef:
              name: etos-environment-provider-database
          - secretRef:
              name: etos-environment-provider-worker-encryption-key
          volumeMounts:
          - name: shared-logs
            mountPath: /home/etos/logs
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 250m
              memory: 512Mi
        - name: sidecar
          image: docker.elastic.co/beats/filebeat:7.10.1
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/filebeat/logs
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
