apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etos-api
  labels:
    app.kubernetes.io/name: etos-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etos-api
  minReplicas: 2
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
