apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: etos-(api|suite-starter|environment-provider|environment-provider-worker)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        secretRef:
          name: etos-rabbitmq

# Update the ESR RabbitMQ secret
replacements:
  - source:
      kind: SealedSecret
      name: etos-rabbitmq
      fieldPath: spec.encryptedData.RABBITMQ_EXCHANGE
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.RABBITMQ_EXCHANGE
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-rabbitmq
      fieldPath: spec.encryptedData.RABBITMQ_HOST
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.RABBITMQ_HOST
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-rabbitmq
      fieldPath: spec.encryptedData.RABBITMQ_PASSWORD
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.RABBITMQ_PASSWORD
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-rabbitmq
      fieldPath: spec.encryptedData.RABBITMQ_PORT
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.RABBITMQ_PORT
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-rabbitmq
      fieldPath: spec.encryptedData.RABBITMQ_SSL
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.RABBITMQ_SSL
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-rabbitmq
      fieldPath: spec.encryptedData.RABBITMQ_USERNAME
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.RABBITMQ_USERNAME
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-rabbitmq
      fieldPath: spec.encryptedData.RABBITMQ_VHOST
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.RABBITMQ_VHOST
      options:
        create: true
