apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: etos-suite-starter
  labels:
    app.kubernetes.io/name: etos-suite-starter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etos-suite-starter
  minReplicas: 2
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
