apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-suite-starter
spec:
  template:
    spec:
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: etos-suite-starter-filebeat-config
      containers:
        - name: etos-suite-starter
          envFrom:
          - configMapRef:
              name: etos-suite-starter-sealed-secret
          - configMapRef:
              name: etos-suite-starter
          - secretRef:
              name: etos-suite-starter-rabbitmq
          volumeMounts:
          - name: shared-logs
            mountPath: /home/etos/logs
        - name: sidecar
          image: docker.elastic.co/beats/filebeat:7.10.1
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/filebeat/logs
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
