apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        /usr/share/filebeat/logs/*
    processors:
      - add_host_metadata:
    output.logstash:
      hosts: ["etos-logstash.etos-staging.svc.cluster.local:5044"]
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: etos-suite-starter
  name: sidecar-config
