apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ./resources/configmaps/suite-runner.yaml
  - ./ingress.yaml

configurations:
  - configurations/namespace.yaml

patches:
- path: ./resources/configmaps/common-config.yaml
- path: ./resources/configmaps/environment-provider-worker.yaml
- path: ./resources/configmaps/suite-starter.yaml
- target:
    kind: Deployment
    name: etos-(api|suite-starter|environment-provider|environment-provider-worker)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: etos
- target:
    kind: Deployment
    name: etos-suite-starter
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: etos-suite-starter
- target:
    kind: Deployment
    name: etos-(environment-provider|environment-provider-worker)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        secretRef:
          name: etos-database
    - op: add
      path: /spec/template/spec/terminationGracePeriodSeconds
      value: 4250

configMapGenerator:
  - name: etos

components:
  # Defaults must be added for us to be able to append to lists that do not
  # have a default value from the base manifests.
  - ../defaults
