apiVersion: v1
data:
  ETOS_DATABASE_HOST: ZXRvcy1wcm9kdWN0aW9uLXJlZGlzLmV0b3MtcHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbA==
  ETOS_DATABASE_PASSWORD: ZXRvc2Rldg==
  ETOS_DATABASE_PORT: MjYzNzk=
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    app.kubernetes.io/instance: etos-production
    app.kubernetes.io/name: etos-environment-provider
  name: etos-environment-provider-database
type: Opaque
