apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-environment-provider-worker
spec:
  template:
    spec:
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: etos-environment-provider-filebeat-config
      containers:
        - name: etos-environment-provider-worker
          envFrom:
          - configMapRef:
              name: etos-environment-provider-sealed-secret-rabbitmq
          - configMapRef:
              name: etos-environment-provider-sealed-secret-database
          - configMapRef:
              name: etos-environment-provider-worker
          - secretRef:
              name: etos-environment-provider-worker-rabbitmq
          - secretRef:
              name: etos-environment-provider-database
          volumeMounts:
          - name: shared-logs
            mountPath: /home/etos/logs
        - name: sidecar
          image: docker.elastic.co/beats/filebeat:7.10.1
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/filebeat/logs
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
