apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: etos-environment-provider-worker-encryption-key
  labels:
    app.kubernetes.io/instance: etos-staging
    app.kubernetes.io/name: etos-environment-provider
spec:
  encryptedData:
    ETOS_ENCRYPTION_KEY: AgB6f8vIPFeoZSrE0oNwbb2KkiT/eTBUf9TV64dDT1zh52tC7VrLnFFxKdwg4gtQPUsSmfoTNxDLIW9kFgZaDHX2pdb4GrMNe3DM51mMcwaaJRAdCAAloE2yRaZ6F4CxW2b9LFPC2KEyKuXKz761XN5AOtVnwwlr7YAKRaRsm+ISswIQkdKRVN+wB9KV3E3li0ZAiyRfguPlMEANhTv0KRTgARxd2Df104bdMSZgHX8z5pCZ2sEJ7Ph8G+ZoHnu87xoTzcEkfhO5IEtLb+j4+fDVFyc9FOcJdHoWV94lYR3Im+1WuwaAldg80WWKxNMmXTRDIRuZmJseQ0Cfl9y3QgBysh4aPej9WpWQ+dgDc9xVSiIYB+YmPHH1C4aCZRQGqUwc8DOUmPgS2MLa5jw7FNhr6i8hfwVmIIWmM0VD9h82Q0xMT6Rqr2nzjnNNf0l1854UjLaRH99Yzcf3bUCbQuAdLxYhXtsl2MB7aISh0n0jbZRKRiQOEWatA4KFQoqDTIrZUoldoa3pJuf6tBcF+B81AYbcdgOeycNjkK/z+AIeFtcffehQFQOCBC8G+Kmvp6G8/yw0hU+UtymVyp6kfGOcYWqj2wwApEuQ+IV6NJgGnnD54JfmnuIQDPGDcnh3HRVIqJUP/SCofaLYjmDoN44OykoSxNxN8G0VI38uHEu7GT7RP7O0qvnEMWotKGi8QuUW6wzFondS6Cx0RmIxee1pZHZUoxaeKehlp9hoNFAC0jlthYRgrw8oDM3bhw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: etos-staging
        app.kubernetes.io/name: etos-environment-provider
      name: etos-environment-provider-worker-encryption-key
    type: Opaque

