apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etos-environment-provider
  labels:
    app.kubernetes.io/name: etos-environment-provider
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etos-environment-provider
  minReplicas: 2
  maxReplicas: 100
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 50
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
