apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: etos-development
    app.kubernetes.io/name: etos-environment-provider-worker
  name: etos-environment-provider-worker-encryption-key
spec:
  encryptedData:
    ETOS_ENCRYPTION_KEY: AgCnBeLz9/Vt7eOKvDKueOAqfMCUv4+uamyUnzk8kNxB3XCh5GiDHPIevoqCD5PZXXKsrPq9btomN8K1ovp7WSdnyh0RFin1YPGmb/P3TZF5efKjUAHvnpSJP2WLzoJmwlJ73iRvWiZ+XbWRipA3Zs0nUAMLh9RVp/GT1BgdRYf8KLjWqECHHuTazBu8cKoTWkpYoFi33f0RoQT0a/ULT37iIsJOQ67MdgOUP0fRCRw6xtSSaW14cUck1mYbeLevMjBKnWMuVx4KGy1KiUUGxok+T0jzpRhCsLz7L7kptlVyqZ/vJdkhuh9g0svpg/5xDNAQ05m4v+T2Vp9KC3i8eUOgXet76KI6KgfOrMvPC1jSlFb5noEIPNKl+XhSPODWphmDymeo6xu5PUUEloBczq1+eKRNEdPBhcIU4LN8uOg53Yhj7KSAv+DtK3ffx+5W6MhO7h8W+AQsW6C0KY1ldbwZIo8CAaRdmc3anSlV3fi65WGOrZyUUE8u3HEdPdT9rFnfBK5WrjLH22yr3krHnnt87W1dWmGc3vLM5bTMqb3S7el/u8RStYrRnI2hQfT5SAHmj7rmiuD9XYoC0AvyDTcstB1Ugal1iy0X4xS0tTMQ1OirQ7yFrrMj2om5Fsp9oXNURf9Tjxff+7F7MJS7EIWGF37USXoXxmAQD48eUydW29UgEQfbvLgWlBuyD1Ra1y8TkWTVlxw0+40LZDG37YCkzbe2MVuM5+u0wy0eGx/gPje+z+9m2z7I7ooSfA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: etos-development
        app.kubernetes.io/name: etos-environment-provider
      name: etos-environment-provider-worker-encryption-key
    type: Opaque

