apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: etos-(api|suite-starter|environment-provider|environment-provider-worker)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom
      value: []
    - op: add
      path: /spec/template/spec/containers/0/env
      value: []
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value: []
    - op: add
      path: /spec/template/spec/volumes
      value: []
