apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "suite-starter.name" . }}-deployment
  
  labels:
    app: {{ include "suite-starter.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "suite-starter.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "suite-starter.name" . }}
        db: redis
    spec:
      {{- if .Values.global.filebeatSidecar.enabled }}
      volumes:
      - name: shared-logs
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: sidecar-config
      {{- end }}
      serviceAccount: {{ .Values.global.serviceAccount.name }}
      containers:
        - name: {{ include "suite-starter.name" . }}
          {{- include "etos.containerImage" . | indent 10 }}
          env:
            - name: RABBITMQ_QUEUE
              value: {{ .Values.rabbitMQ.queue_name }}
            - name: RABBITMQ_ROUTING_KEY
              value: {{ .Values.rabbitMQ.routing_key }}
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: password
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: username
          envFrom:
          - configMapRef:
              name: etos
        {{- if .Values.global.filebeatSidecar.enabled }}
          volumeMounts:
          - name: shared-logs
            mountPath: /home/etos/logs
        - name: sidecar
          image: {{ .Values.global.filebeatSidecar.image }}
          volumeMounts:
          - name: shared-logs
            mountPath: /usr/share/filebeat/logs
          - name: filebeat-config
            mountPath: /usr/share/filebeat/filebeat.yml
            readOnly: true
            subPath: filebeat.yml
        {{- end }}
