apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "environment-provider.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "environment-provider.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "environment-provider.name" . }}
        db: redis
    spec:
      serviceAccountName: {{ .Values.global.serviceAccount.name }}
      containers:
        - name: {{ include "environment-provider.name" . }}
          {{ include "etos.containerImage" . | indent 10 }}
          command:
            - "./entry.sh"
          env:
            - name: ETOS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: password
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: password
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: username
          envFrom:
          - configMapRef:
              name: etos          
          ports:
              - containerPort: 80
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "app"
                      operator: In
                      values:
                      - {{ include "environment-provider.name" . }}
                topologyKey: "kubernetes.io/hostname"  