apiVersion: v1
kind: Service
metadata:
  name: {{ include "environment-provider.name" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ include "environment-provider.name" . }}
  type: ClusterIP
status:
  loadBalancer: {}
