apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: etos-environment-provider-database
spec:
  encryptedData:
    ETOS_DATABASE_HOST: AgAmY8tDD8W86keOVtYsvNbVNO+wRiUcC1YhvQXp8FgBXQnkn1CKJkc6DrpJ1TRuGU6ddU3muvem6gXp++dcsnvV9Ue9F4sKNEDuFC5z+Z61r22D6tRzluUHeQZilXVGmZ2Yij4qgihewjY5OyMMN/Ehrsb2otVZccgPYc4sRUeUEdfYUzbtGACZz3v68PFkVaAIWt/jS9mMX1DlcXCyvaQKTKLbMF4cxLlcsXT0W1pN+dPRzqjVn8zGsz5RT6QuooRJ79r5xsk+ok1A8MaOZ/OwcUbCRXjf0b/DEol0eTok+k6R/iKknpBdQH9p4iYB5kOzmXeKt9FiHn2Noosn0zOW6CLv7nAQN3nPKqbFjDn+ZZovpyI50rU481t8ztv9LM6F6MqfrACjPvMLfezzvtBjiWoplPd5OyPkpVxxCI6KqCERnFX5s4kuPCwesvi5MdK3Go5pxybKEFZF2zOVYZGI2LbOisl7734Jf5l292+Vwnfio25QoT/oYevi+kYpAi5tPMySTDVlk1ndwR74lUfVk5hFJCA3MYp917oyu4/26dnQtN9e7jjh6z3WNNW+jW2+AC432oCnJBKqY/6TZgA5qDYNbGUMHd2pkVWnqZEc2Jzhs7JiOw05Ni4LXIg4schK7BWXudSNbAestKvlRVhx4fhmhEp02XQySCs2XyDsbD793CXTKU/j0YGpXmkPzmmTtj1+0l/yOAHzXaRjhGf3jAQ384wEh24FjznnqZwzJBofDbm+n/42/jO6ahBrYKIFPPhhX4WI6Xw=
    ETOS_DATABASE_PASSWORD: AgCtPcPggmvFj1DAMp0y83p9JgSHP2kt9MStkfv3fY9KAvsNk8oFuJX2P/YOYZq3YmaBnxLfsYOU3Bpkl43pEapzJuG/6oKOsvFZiLmI+bh4PNnEZ6hZngfRZEQlZGFvR0Gu9yG/d1CKdMrNLJz9+0qUiZ+7QAfvFK/3QBzK0UyTubC45vw+1KfAqKRrqdk+BqcoJ7fAihJ2nOitNXXbDaPQr3xyqJIYX55dq+9TcDBGyjtu3YtZ7XsjqMqpDuNcL9GqmZnRjRBwEn9zjHQ1ALLn68Fd0Q7DUBZAa9xU6QHI1IZep1oaP+1YiR0cYmxy/QNyKD1Z+JyQqfRD5nzpkkANhhcVlUs5r9jDElgQGQ1wPx9kcGhsXKumBzSrV+8TSwukmq0hhxtMRUwPkIA1BPShK//Quw/MubcvJ2gHRKf8zGLPdRDvyz5Up2fCbzmzcgcYptB7oYQCmFO00FX8WnE72ALioMFuKRnVOuqqZ3+Sp80PX8ccoF1ts0Dr4dGOcQRYyMNt1AS1/qWCdWEh6+mvWikYwDz+95DxDwA72Q0+18yKl2ek8V7ia99Y4AawcW/gHbNy3r5XxSBcd8feH7f/NdjF8h++DHJzJOQywBULCqkNLSMVW1IbZwieSE0Ucont6pNDOl4lV1i6pzrxf5lrnI3j3mQCQYfiZPyBAmhj41SxN7bz41o6Pm0mMp/Eo5qeNqA4RSlR
    ETOS_DATABASE_PORT: AgCymJ3T8x7hwDZ1BWSichGRG0ExIxvecIuQ+4QM/tGT3CCTVlEa+HBEgNbpN/pSckkHVwrYX/O22fWQrr3Dp2JDdSqL1zsJt4ABWkpnUXMxqQdUCoJuBzWBZh8cs2Xpdvd7nP4cXOlk97+73yYm2KZ7Ez0nHDBdg2GNfGOhHJvva4ZW64NjeQyNM9fylfHoVKFeBxGHT8fmkb4sgPWrg2Jl+harbknahenDMoml+3s06pG65ZvejOdV4IXpMiBIRCOW0otgZdAIVmGebz16+LlyIdfXhIXWWkozuM/mmxgaDBP9+fpuwRoCoFNt4fBlpEZfNfQ3mvd43TZvdjj4vOB7RvyyR2yca11GJqdHLJJPrKe7U9ZWCYrTToOB9ldChynMB97JeJv5TDTvbrZkZRnVTbG5g/FP1gMLeI5qTXj66m9gPBpAti4MmipGU3kaoVuZggNzXyQOYL1V8TbFovugLAnZL9IIrNJqBW8xxKWfg3XNNiDI3dPYJLOwbsxTQEOfV1+ZMELL5z6UyYVqIEqnjkehOkg0xnZpUbE21PWvqDuOZuck0IpWxeToMYsEPJ0pmEtOrRjAJcKjkX+IrQddNXgL/ZcMCxpJwP4C29h5ocfdE8+0mgu04nL3ICwIcA+mepYe45H9HW6QQOZCCSBAB+oqVIEJ7KImScHUPVk0jeUyr+TZBipTHjKtTYHZNNTaBMzAZg==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: etos-environment-provider
      name: etos-environment-provider-database
    type: Opaque

