apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

configMapGenerator:
  - name: reload
    behavior: create

patches:
- target:
    kind: Deployment
    name: etos-(api|suite-starter|environment-provider|environment-provider-worker)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: reload
