apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ include "etos-api.name" . }}
  name: {{ include "etos-api.name" . }}
spec:
  rules:
  - host: {{- include "etos-api.host" . | indent 1 }}
    http:
      paths:
      - backend:
          serviceName: {{ include "etos-api.name" . }}
          servicePort: http
        path: /
