apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - role.yaml
  - service-account.yaml
  - rolebinding.yaml
  - service.yaml
  - deployment.yaml


# By generating the configmap it will get a unique name on each apply
# this name is also set on the deployment. This means that the pods
# will restart with the new configmap when changes are made. Making
# it so we do not have to do rollout restart every time.
configMapGenerator:
  - name: etos-firmware-flasher
    literals:
      - FIRMWARE_FLASH_DEADLINE="600"
      - FIRMWARE_FLASH_DOCKER=docker-prod.se.axis.com/nemesis/suite_runner/firmware_flasher:1.14.0
