apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-environment-provider
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: execution-space-providers
          secret:
            secretName: execution-space-providers
        - name: log-area-providers
          secret:
            secretName: log-area-providers
        - name: iut-providers
          secret:
            secretName: iut-providers
      containers:
        - name: etos-environment-provider
          env:
            - name: EXECUTION_SPACE_PROVIDERS
              value: /providers/execution_space
            - name: LOG_AREA_PROVIDERS
              value: /providers/log_area
            - name: IUT_PROVIDERS
              value: /providers/iut
          envFrom:
          - configMapRef:
              name: etos-environment-provider-secrets
          - configMapRef:
              name: etos-environment-provider
          - secretRef:
              name: etos-environment-provider-database
          volumeMounts:
            - name: execution-space-providers
              readOnly: true
              mountPath: "/providers/execution_space"
            - name: log-area-providers
              readOnly: true
              mountPath: "/providers/log_area"
            - name: iut-providers
              readOnly: true
              mountPath: "/providers/iut"
