apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-api
spec:
  template:
    spec:
      containers:
      - name: etos-api
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 196Mi
