apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Deployment
    name: etos-(suite-starter|environment-provider-worker)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        secretRef:
          name: etos-user-log
- target:
    kind: Deployment
    name: etos-(api|environment-provider)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: ETOS_ENABLE_SENDING_LOGS
        value: "false"

# Update the ESR RabbitMQ secret
replacements:
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_QUEUE_NAME
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_QUEUE_NAME
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_QUEUE_PARAMS
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_QUEUE_PARAMS
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_EXCHANGE
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_EXCHANGE
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_HOST
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_HOST
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_PASSWORD
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_PASSWORD
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_PORT
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_PORT
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_SSL
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_SSL
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_USERNAME
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_USERNAME
      options:
        create: true
  - source:
      kind: SealedSecret
      name: etos-user-log
      fieldPath: spec.encryptedData.ETOS_RABBITMQ_VHOST
    targets:
    - select:
        kind: SealedSecret
        name: etos-suite-runner-rabbitmq
      fieldPaths:
      - spec.encryptedData.ETOS_RABBITMQ_VHOST
      options:
        create: true
