apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-environment-provider-worker
spec:
  template:
    spec:
      containers:
      - name: etos-environment-provider-worker
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 512Mi
