apiVersion: apps/v1
kind: Deployment
metadata:
  name: etos-suite-starter
spec:
  template:
    spec:
      containers:
      - name: etos-suite-starter
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
