apiVersion: v1
kind: Service
metadata:
  name: etcd-client
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: etos
spec:
  type: ClusterIP
  ports:
  - name: etcd-client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: etos
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: etos
spec:
  clusterIP: None
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/part-of: etos
