name: Tox

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tox:
    name: run-tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Tox
        run: pip install tox
      - name: Upgrade setuptools
        run: pip install -U setuptools
      - name: Run Tox
        run: tox
        working-directory: ./cli
