name: Validate suite schema

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Validate suite example against schema
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install check-jsonschema
        run: pip install check-jsonschema

      - name: Validate example against JSON schema
        run: |
          check-jsonschema \
            --schemafile schemas/suite/v1alpha1/suite.schema.json \
            schemas/suite/v1alpha1/example.yaml
